apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: web
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-vhost-config
data:
  wordpress.example.net.conf: |
    <VirtualHost *:80>
        ServerAdmin admin@example.com
        ServerName wordpress.example.com
        DocumentRoot /var/www/html/
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: apache-config1
# data:
#   apache2.conf: |
#     ServerName 127.0.0.1
#     ServerName wordpress.example.net
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: web
    spec:
      containers:
      - image: wordpress:php8.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-wp
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/www/html
        - name: apache-config
          mountPath: /etc/apache2/sites-available
        # - name: apache-config1
        #   mountPath: /etc/apache2/
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
      - name: apache-config
        configMap:
          name: apache-vhost-config
      # - name: apache-config1
      #   configMap:
      #     name: apache-config1